More changes Fail2Ban Ubuntu support

diff --git a/extra/fail2ban/domban b/extra/fail2ban/domban
--- a/extra/fail2ban/domban
+++ b/extra/fail2ban/domban
@@ -147,6 +147,11 @@ install_fail2ban_ufw()
     exit 1
   fi
 
+  if [ ! -e /etc/fail2ban/action.d/ufw.conf ]; then
+    log_err "UFW Fail2Ban action not found - Skipping configuration!"
+    exit 1
+  fi
+
   echo
   echo "UFW detected"
   echo
