fail2ban improvements and documentation

diff --git a/extra/fail2ban/domban b/extra/fail2ban/domban
--- a/extra/fail2ban/domban
+++ b/extra/fail2ban/domban
@@ -1,6 +1,107 @@
 #!/bin/bash
 
 
+
+
+check_file_busy()
+{
+  if [ ! -e "$1" ]; then
+    return 0
+  fi
+
+  local TARGET_REAL_BIN=$(readlink -f $1)
+  local FOUND_TARGETS=$(lsof "$TARGET_REAL_BIN" 2>/dev/null | grep "$TARGET_REAL_BIN")
+
+  if [ -n "$FOUND_TARGETS" ]; then
+    return 1
+  else
+    return 0
+  fi
+}
+
+nsh_cmp()
+{
+  if [ -z "$1" ]; then
+    return 1
+  fi
+
+  if [ -z "$2" ]; then
+    return 1
+  fi
+
+  if [ ! -e "$1" ]; then
+    return 1
+  fi
+
+  if [ ! -e "$2" ]; then
+    return 1
+  fi
+
+  if [ -x /usr/bin/cmp ]; then
+    cmp -s "$1" "$2"
+    return $?
+  fi
+
+  HASH1=$(sha256sum "$1" | cut -d" " -f1)
+  HASH2=$(sha256sum "$2" | cut -d" " -f1)
+
+  if [ "$HASH1" = "$HASH2" ]; then
+    return 0
+  fi
+
+  return 1
+}
+
+install_file()
+{
+  SOURCE_FILE=$1
+  TARGET_FILE=$2
+  OWNER=$3
+  GROUP=$4
+  PERMS=$5
+
+  if [ ! -r "$SOURCE_FILE" ]; then
+    echo "[$SOURCE_FILE] Can not read source file"
+    return 1
+  fi
+
+  if [ -e "$TARGET_FILE" ]; then
+
+    nsh_cmp "$SOURCE_FILE" "$TARGET_FILE"
+    if [ $? -eq 0 ]; then
+      echo "[$TARGET_FILE] File did not change -- No update needed"
+      return 0
+    fi
+
+    if [ ! -w "$TARGET_FILE" ]; then
+      echo "[$TARGET_FILE] Can not update file -- No write permissions"
+      return 1
+    fi
+
+    check_file_busy "$TARGET_FILE"
+
+    if [ $? -eq 1 ]; then
+      echo "[$TARGET_FILE] Error - Can not update file -- File in use"
+      return 1
+    fi
+  fi
+
+  cp -f "$SOURCE_FILE" "$TARGET_FILE"
+
+  if [ -n "$OWNER" ]; then
+    chown $OWNER:$GROUP "$TARGET_FILE"
+  fi
+
+  if [ -n "$PERMS" ]; then
+    chmod "$PERMS" "$TARGET_FILE"
+  fi
+
+  echo "[$TARGET_FILE] copied"
+
+  return 2
+}
+
+
 print_delim ()
 {
   echo "--------------------------------------------------------------------------------"
@@ -15,6 +116,7 @@ log_err()
 
 fail2ban()
 {
+  SCRIPT_DIR=$(dirname $0)
 
   if [ "$EUID" = "0" ]; then
     SUDO=
@@ -50,19 +152,21 @@ fail2ban()
     echo
     echo "Syntax: domban"
     echo
-    echo "ssh              Shows status of SSH jail"
-    echo "unblock <IP>     Unblocks IP from Domino and SSH jail"
-    echo "cfg              Configures fail2ban jail.local. Default editor: vi. Use e.g. export EDIT_COMMAND=nano"
-    echo "restart          Restarts fail2ban service"
+    echo "ssh              Show status of SSH jail (no parameter = show Domino jail)"
+    echo "unblock <IP>     Unblock IP from Domino and SSH jail"
+    echo "cfg              Configure fail2ban jail.local. Default editor: vi. Use e.g. export EDIT_COMMAND=nano"
+    echo "log <lines>      List fail2ban log (default: last 100 lines)"
+    echo "status           Show systemd fail2ban status"
+    echo "restart          Restart fail2ban service"
     echo "systemd <cmd>    Pass commands to systemd"
-    echo "install [upd]    Installs fail2ban and 'domban' script - 'upd' overwrites existing 'jail.local'"
+    echo "install [upd]    Install fail2ban and 'domban' script - 'upd' overwrites existing 'jail.local'"
     echo "test <logfile>   Test Domino fail2ban filter against log - if no log file specified use configured log file"
     echo "-                No parameter shows Domino jail status"
     echo
-    echo "selinux          Shows SELinux status" 
-    echo "selinux logset   Lables start script log file with fail2ban access" 
-    echo "selinux logdel   Removes label for start script log" 
-    echo "selinux relable  Relables log files" 
+    echo "selinux          Show SELinux status"
+    echo "selinux logset   Lable start script log file with fail2ban access"
+    echo "selinux logdel   Remove label for start script log"
+    echo "selinux relable  Relable log files"
     echo
    
     return 0
@@ -79,21 +183,20 @@ fail2ban()
     yum install epel-release 
     yum install fail2ban
 
-    cp domino.conf /etc/fail2ban/filter.d/domino.conf
+
+    install_file "$SCRIPT_DIR/domino.conf" "/etc/fail2ban/filter.d/domino.conf" root root 644
+    install_file "$SCRIPT_DIR/domban" "/usr/bin/domban" root root 755
 
     if [ -e /etc/fail2ban/jail.local ]; then
 
       if [ "$2" = "upd" ]; then
-        cp jail.local /etc/fail2ban/jail.local
+        install_file "$SCRIPT_DIR/jail.local" "/etc/fail2ban/jail.local" root root 644
       else
         log_err "Please review '/etc/fail2ban/jail.local' or use 'install upd' to overwrite existing config!"
       fi  
     else
-      cp jail.local /etc/fail2ban/jail.local
+      install_file "$SCRIPT_DIR/jail.local" "/etc/fail2ban/jail.local" root root 644
     fi
-
-    cp -f domban /usr/bin/domban
-    chmod 755 /usr/bin/domban
 
     systemctl enable fail2ban
     systemctl restart fail2ban
@@ -159,13 +262,25 @@ fail2ban()
     return 0
   fi
 
-  # systemd status 
+  # systemd status
+  if [ "$1" = "status" ]; then
+      echo
+      print_delim
+      systemctl status fail2ban
+      print_delim
+      echo
+
+      return 0
+  fi
+
+
+  # systemd commands
   if [ "$1" = "systemd" ]; then
 
     if [ -z "$2" ]; then
       echo
       print_delim
-      $SUDO systemctl status fail2ban  
+      systemctl status fail2ban
       print_delim
       echo
       return 0
@@ -183,6 +298,34 @@ fail2ban()
     return 1 
   fi
 
+  # Show fail2ban log
+  if [ "$1" = "log" ]; then
+
+    if [ -z "$2" ]; then
+      tail -100 /var/log/fail2ban.log
+      return 0
+    fi
+
+    if [ "$2" = "edit" ]; then
+      $EDIT_COMMAND /var/log/fail2ban.log
+      return 0
+    fi
+
+    if [ "$2" = "more" ]; then
+      more /var/log/fail2ban.log
+      return 0
+    fi
+
+    case "$2" in
+      [0-9]*)
+        tail -$2 /var/log/fail2ban.log
+        return 0
+        ;;
+    esac
+
+    log_err "Unkown log option: $2"
+    return 1
+  fi
 
   # Test Domino filter against log 
   if [ "$1" = "test" ]; then
@@ -190,7 +333,20 @@ fail2ban()
     if [ -z "$2" ]; then
       TEST_LOG="$DOMINO_OUTPUT_LOG"
     else
-      TEST_LOG="$2"
+
+      case "$2" in
+        -*)
+          TEST_PARAM="$2"
+          ;;
+
+        *)
+          TEST_LOG="$2"
+          ;;
+      esac
+
+      if [ -n "$3" ]; then
+        TEST_PARAM="$3"
+      fi
     fi
 
     if [ ! -r "$TEST_LOG" ]; then
@@ -203,7 +359,7 @@ fail2ban()
     echo "Testing $TEST_LOG"
     print_delim
 
-    fail2ban-regex "$TEST_LOG" /etc/fail2ban/filter.d/domino.conf
+    fail2ban-regex "$TEST_LOG" /etc/fail2ban/filter.d/domino.conf $TEST_PARAM
 
     print_delim
     echo
